# Generated by Django 4.2.6 on 2023-10-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('apelido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telefone', models.IntegerField(max_length=9)),
            ],
        ),
    ]
